import pandas as pd
import re
import os

def process_fixations_to_movements(participant_id, csv_path, trial_order=None, block_order=None):
    """
    Parses the fixation CSV and returns a long-format DataFrame of movements.
    
    Args:
        participant_id (str): ID of the participant.
        csv_path (str): Path to the CSV generated by Convert_eye_data.m.
        trial_order (list, optional): List of trial numbers to map rows.
        block_order (list, optional): List of block numbers to map rows.
        
    Returns:
        pd.DataFrame: Columns [participant_id, movement_type, trial, block]
    """
    
    if not os.path.exists(csv_path):
        print(f"File not found: {csv_path}")
        return pd.DataFrame()

    # Read CSV (No header, variable columns)
    # The MATLAB script uses writecell, so it might not have a header.
    # Rows are trials. Columns are fixations.
    try:
        df = pd.read_csv(csv_path, header=None)
    except pd.errors.EmptyDataError:
         print(f"Empty CSV: {csv_path}")
         return pd.DataFrame()

    movements = []

    # Iterate over trials (rows)
    for index, row in df.iterrows():
        # Determine trial and block info
        # If orders are provided, use them. Otherwise, default to index + 1
        trial_num = trial_order[index] if trial_order and index < len(trial_order) else index + 1
        block_num = block_order[index] if block_order and index < len(block_order) else 1 # Default block 1
        
        # Get fixation sequence for this trial
        # Filter out NaNs
        fixations = row.dropna().astype(str).tolist()
        
        # Analyze transitions
        for i in range(len(fixations) - 1):
            prev_aoi = fixations[i]
            curr_aoi = fixations[i+1]
            
            # Logic from classifyScanHV.m
            # Parse A# / B#
            # Pattern: ^([AB])(\d+)$
            
            pattern = r"^([AB])(\d+)$"
            match_prev = re.match(pattern, prev_aoi)
            match_curr = re.match(pattern, curr_aoi)
            
            mov_type = "other"
            
            if match_prev and match_curr:
                col_prev, row_prev = match_prev.groups()
                col_curr, row_curr = match_curr.groups()
                
                # Check for standard repetition (ignore A1->A1?)
                if col_prev == col_curr and row_prev == row_curr:
                    continue # Ignore repetition
                
                # Logic:
                # Vertical: Same Column (Letter), Different Row (Number) -> A1 to A2
                # Horizontal: Different Column (Letter), Same Row (Number) -> A1 to B1
                
                if col_prev == col_curr and row_prev != row_curr:
                    mov_type = "v"
                elif col_prev != col_curr and row_prev == row_curr:
                    mov_type = "h"
                else:
                    mov_type = "other" # Diagonal or other
                    
            # Add to list
            movements.append({
                "participant_id": participant_id,
                "movement_type": mov_type,
                "trial": trial_num,
                "block": block_num,
                # Optional: "transition": f"{prev_aoi}->{curr_aoi}"
            })
            
    return pd.DataFrame(movements)

def calculate_indices(movements_df):
    """
    Calculates H / (H + V) index per trial (and block).
    Matches the logic of classifyScanHV.m
    """
    if movements_df.empty:
        return pd.DataFrame()
        
    # Filter only h and v
    hv_df = movements_df[movements_df['movement_type'].isin(['h', 'v'])]
    
    # Group by trial and block
    grouped = hv_df.groupby(['participant_id', 'block', 'trial', 'movement_type']).size().unstack(fill_value=0)
    
    # Ensure h and v columns exist
    if 'h' not in grouped.columns: grouped['h'] = 0
    if 'v' not in grouped.columns: grouped['v'] = 0
    
    grouped['total'] = grouped['h'] + grouped['v']
    grouped['index'] = grouped['h'] / grouped['total']
    
    return grouped.reset_index()
